### ISSUE TITLE
multiple signatures - alternative solution

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#1]
The current scheme was _partially_ derived from the JSON Serialized JWS.

**Single signature**:

&nbsp;&nbsp;"signature": {
&nbsp;&nbsp; &nbsp;&nbsp;_Complete signature_
&nbsp;&nbsp;  } 

**Multiple signatures**:

&nbsp;&nbsp;"signatures": [{
&nbsp;&nbsp; &nbsp;&nbsp;_Complete signature_
&nbsp;&nbsp;}...]

Although working this scheme has limitations wrt to `crit` and the proposed `excl` extension [1] making an alternative solution worth considering:

**Single signature**:

&nbsp;&nbsp;"signature": {
&nbsp;&nbsp; &nbsp;&nbsp;_Global_
&nbsp;&nbsp; &nbsp;&nbsp;_Signature specific_
&nbsp;&nbsp;  } 

**Multiple signatures**:

&nbsp;&nbsp;"signature": {
&nbsp;&nbsp;&nbsp;&nbsp;_Global_
&nbsp;&nbsp;&nbsp;&nbsp;"multiple": [{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Signature specific_
&nbsp;&nbsp;&nbsp;&nbsp;}...]
&nbsp;&nbsp;  } 

Constraints:
Optional `crit` and `excl` specifiers MUST be in the _Global_ section only.
Properties specified by `crit`  MUST be in the _Signature specific_ section(s) only.
Properties specified by `excl` MUST be in the _Application level_ only only.

**Advantages/features:**
- A more logical and stringent `crit` feature
-  `excl` would always refer to the application level object (where it makes sense)
- A _Global_ `alg` would force all signatures to use that 
- Analogous to JWE as shown by the following sample using both a shared `alg` and a `crit` extension:

```json
{
  "aMutiplySignedProperty": "This is it!",
  "signature": {
    "alg": "ES256",
    "crit": ["who"],
    "multiple": [{
      "who": "Jane Doe",
      "val": "ZGJjHfoBPAfk3OC3DSoJwW4Rtkwl-oS--I1h8ogq3oEx8ncJ0R_BOfX9mxlX9K-zW4e1d46CikhNWyi2wKnsKw"
    },{
      "who": "John Doe",
      "val": "LZB2awEHZbK48Zgnm-zLlyLmFMArP2vMvjN_RfUhF72iQPDT4Gee-n8S0kDTdXsZfCs5mCoBU_rFLdS-lddBbS"
    }]
  }
}
```
**1] The `excl` property**

_Optional_ array holding the names of one or more properties featured on the same level as the `signature` property, that MUST be excluded from the signature process.

Note that the `excl` property itself, MUST also be excluded from the signature process.

Property names that are to be excluded from the signature process MUST NOT be duplicated or try to override `signature`.

A conforming implementation MUST reject signatures listing properties that are not found as well as empty `excl` objects. Verifiers are RECOMMENDED introducing additional constraints like only accepting predefined properties.  Sample:
```json
{
  "mySignedData": "something",
  "myUnsignedData": "something else",
  "signature": {
    "alg": "ES256",
    "jwk": {
      "kty": "EC",
      "crv": "P-256",
      "x": "2zlYOKuQmOswt_xo_XhizgABDn8w2qUlte5ALXYpTWM",
      "y": "wcezP2ejoD6hwPrWNYPTPSteTmWKxMR8V04ryixmXLA"
    },
    "excl": ["myUnsignedData"],
    "val": "mjmbl9GjkGFwCgdvnx6zM_X0cYrxFm2EEdJ6s_DB3caiRfIj5hE5F4d_2dNkyE4ZqVrKUUKnE27oN2pW0IVlSw"
  }
}
```
The application for `excl` is enabling a party somewhere in the middle acquiring data in a signed object that can be "consumed" and letting the party sent the revised data to yet another party.

**Comment by erdtman** [comment]
First I would like to split out excl to a separate issue because I think that is orthogonal to the question of how to represent Multiple signatures.

I can see that by changing the structure to look like this it would be more similar to the suggestion for encryption, which is good. However the thing I liked with the current solution is that I get a set of headers/attributes and I don´t have to worry about global vs local.

So I have no strong preference, to me it is just different ways of doing the same thing.

**Comment by cyberphone** [comment]
> First I would like to split out excl to a separate issue because I think that is orthogonal to the question of how to represent Multiple signatures.

You are absolutely right.

> So I have no strong preference, to me it is just different ways of doing the same thing.

For support of `crit` I believe the change would be beneficial (more "logical"), but you are technically completely right.

**Comment by cyberphone** [comment]
It is also possible making `crit` analogous to how `alg` would work.  Either Global or Local, never both.  That is, `crit` can either be signature specific or the same for all.

**Comment by selfissued** [comment]
Use __cleartext_signature for top-level name.  Use "signers" for array.  Use "signature" for signature.

For JWE, use "recipients" for array name.  Use JWE JSON Serialization names for everything that we can.

**Comment by selfissued** [comment]
Our examples/test vectors need to include both single-signature and multiple-signature examples.

**Comment by erdtman** [comment]
When writing the text for this remember this.
Reusing the existing JOSE decisions, values like "alg" could be at either level when there are multiple parties, but not both.
CT-JWE has text for this

**Comment by erdtman** [comment]
@cyberphone how is it going with this?

**Comment by cyberphone** [comment]
I haven't yet written any text for this, I'm still a bit "fixated" with the implementation.  My original implementation for multiple signatures "works" but was actually quite stupid :-(  Multiple signatures (unlike multiple encryptions), are presumably created one by one so you need something like an `addSignature()` where there initially is no signature.  Not rocket science but not exactly trivial either since you have to re-parse the object to be signed every time as well.

**Comment by cyberphone** [comment]
It is not dead at least. This verifiable sample should be compatible with the (not yet written) specification:
```json
{
  "now": "2018-04-16T11:23:06Z",
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "__cleartext_signature": {
    "signers": [{
      "alg": "ES256",
      "jwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
        "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY"
      },
      "signature": "RNVdjbCD3rdJNuMxlWI8UZGxfRzTjFA5xc5-R1ysSsn8jMdGQnTkOWftqfKpySz8WuOAUi3bxdSMp4FxYI9c9w"
    },{
      "alg": "RS256",
      "jwk": {
        "kty": "RSA",
        "n": "hFWEXArvaZEpSP5qNX7x4C4Hl28GJQTNvnDwkfqiWs63kXbdyPeS06bz6GnY3tfQ_093nGauWsimqKBmGAGMPtsV83Qxw1OIeO4ujbIIb9pema0qtVqs0MWlHxklZGFkYfAmbuEUFxYDeLDHe0bkkXbSlB7_t8pCSvc8HLgHjEQjYOlFRwjR0D-uLo-xgsCbpmCtYkB5lcT_zFgpRgY4zJNLSv7GZiz2S4Fc5ArGjd34lL47-L8bozuYjqNOv9sqX0Zgll5XaJ1ndvr7UqZu1xQFgm38reoM3IarBP_SkEFbt_v9iak602VO3k28fQhMaocP7JWR2YLT3kZM0-WTFw",
        "e": "AQAB"
      },
      "signature": "JcdhAZrOw7ziqJ1wvV2PmslANHMXpMICcrnkaTHcLkN5zxKqW_b3KvILCCDULzhLbQL3I7Evt5cfXF917DQNBNPuWI46AmUMAnGT8JoMtxVY2LmDA8qVZNeVsbxHWhQ_A5MLlxkvFXCquMMeVUJ1U7gA0gFbh2X77Uj4IJOBkJobPaC3kKJDiz78kn3FErG9LAzIEsw-OwbwyPGN6t1N-kdLtE9VN_4bgu3YWcS7nDZB0oju1ia_TINwa1l1MFBG61MCuD93ISZML4qn9dRqaQEjMh3NAhqh6pV-U9QrchaMnqH4ZmQHsLs1Gq9Rt6Biv9NohfZ72s_iR_QU7spL8g"
    }]
  }
}
```
The only thing not being a part of normalization are 
- the commas separating signature objects
- the "signature" property

Applied to the first signature:
```json
{
  "now": "2018-04-16T11:23:06Z",
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "__cleartext_signature": {
    "signers": [{
      "alg": "ES256",
      "jwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
        "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY"
      }
    }]
  }
}
```
And yes, the signatures are separated from each other so you must remove all signature objects except the one you want to validate!

**Comment by erdtman** [comment]
Looks good to me!

**Comment by erdtman** [comment]
It does not show in the examples but if the same algorithm was used by all signers it should have been moved up to "global" level, right? 
And when only having one signer only "global" level should be used, right?

**Comment by cyberphone** [comment]
> It does not show in the examples but if the same algorithm was used by all signers it should have been moved up to "global" level, right?
And when only having one signer only "global" level should be used, right?

May I comment on this from an implementer's point of view? Although it would look nice, I don't want to make this a **requirement** because most implementations would probably work like mine where you _add one signature at a time_ and possibly not even in the same environment.  If we stick to the single level only rule, the first signature will effectively set the rule for subsequent signatures.  The following sample was created with a signature API _option_ to use a global "alg" (which obviously fails if a non-conforming signature or algorithm is added):

```json
{
  "now": "2018-04-16T11:23:06Z",
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "__cleartext_signature": {
    "alg": "ES512",
    "signers": [{
      "jwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
        "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY"
      },
      "signature": "VDwM4TTIFBxxcqOkn2auAnahWy2w8d1UVawSLW1wS0mlkwEybaaoZHJ-91TWMexTJ_Q5TocIszGpSg7vSXf63Q"
    },{
      "jwk": {
        "kty": "EC",
        "crv": "P-384",
        "x": "GLfdsvEwphRzS_twup7UFPVOk7_CKgHZ7dt_fJ2QHPBdJa1c5pfJcRIWTfT0lpg9",
        "y": "ovA5_QXmFbj9U4pjZ1AX_ZdVyIRZUBWW9cuZda_tupKfWQfmcQHzDmHGHbxl9Xxl"
      },
      "signature": "lzyiteU3FOUBo5HFyskW8b6OnWdDWByNCNqA0wiCrnzLhJD1DCGiVYBTE2kyRC4ulKUqS_RDPfcGkGBZ6YTuQAbjOQQybHHcv7AYaAXH73JYzVut5isq2epww1u--bFI"
    }]
  }
}
```

**Comment by cyberphone** [comment]
The global/local thing is not really a "killer feature".  After implementing it which was simple, I see that it won't save many bytes and the ability to "lock" an algorithm is probably better to enforce at the API level (or JSON schema) which is a more generic solution.

That is, I would consider nuking this.

WDYT?

**Comment by cyberphone** [comment]
sorry I pressed the wrong button :-)

**Comment by selfissued** [comment]
The global/local feature is an important part of the JWS JSON Serialization and the JWE JSON Serialization.  We should faithfully reflect the same semantics in our Cleartext syntax.

**Comment by selfissued** [comment]
And I agree with @erdtman that in our examples, if the same algorithm is used by all signers, "alg" should be in the global level.

**Comment by erdtman** [comment]
@cyberphone are you suggesting that we keep to the current solution, with the __cleartext_signature(s) being either a single signature object or an array of signatures objects?

**Comment by selfissued** [comment]
The example looks fine to me - other than that it's actually not normal practice to include the JWK key representation in the JWS.  Keys are typically referenced by "kid" and not included inline.

This is for trust reasons.  Sure, anyone can easily validate a signature when there's a JWK included saying "validate me with this key" but attackers can just as easily provide keys as legitimate parties.  That's why, for instance, OpenID Connect prohibits the inclusion of the "jwk" header parameter in JWTs.

I'd rather that we remove the "jwk" values from the example JSON and instead put them (and their corresponding private keys) in another section.  That still lets people validate and reproduce the examples, but doesn't utilize a bad security practice in our examples.  Thanks.

**Comment by cyberphone** [comment]
Without going into the security discussions I will then produce samples without in-line JWKs.

**Comment by cyberphone** [comment]
Does this cover your concerns as well as https://github.com/erdtman/Cleartext-JOSE/issues/41 ?
```json
{
  "iss": "joe",
  "exp": 1300819380,
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "__cleartext_signature": {
    "alg": "ES512",
    "signers": [{
      "kid": "example.com:p256",
      "signature": "zjf2MzEesdIudTk0k9osa0um5ffzU-oM_8Z-mKHFmZxCRvpl41lX2KUt5a742px_cTsG7sw-Kh8_xJuUMX97Kg"
    },{
      "kid": "example.com:p384",
      "signature": "jTWnzmAcC34zOpTvvg7vuqLECUOqS6UMQcjwM24w7DwHz7nXQe17eFYTjJWE-w_Nnw3sosYM6c6J9ABFOGoKx70cRPNQQ8WHfTzAyfTBxMBWtUR5PKWi5hJWUDeMnRS0"
    }]
  }
}
```
Test key **example.com:p256**:
```json
{
  "kid": "example.com:p256",
  "kty": "EC",
  "crv": "P-256",
  "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
  "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY",
  "d": "nEsftLbi5u9pI8B0-drEjIuJzQgZie3yeqUR3BwWDl4"
}
```
Test key **example.com:p384**:
```json
{
  "kid": "example.com:p384",
  "kty": "EC",
  "crv": "P-384",
  "x": "GLfdsvEwphRzS_twup7UFPVOk7_CKgHZ7dt_fJ2QHPBdJa1c5pfJcRIWTfT0lpg9",
  "y": "ovA5_QXmFbj9U4pjZ1AX_ZdVyIRZUBWW9cuZda_tupKfWQfmcQHzDmHGHbxl9Xxl",
  "d": "Qsgq80kMs40sAn1gB7gLxAk1se37Kmh9AG18wWZ3SqgcPPRq1wwidNTi866Gt4_0"
}
```
What's currently missing is "converting" test data so it conforms to the slightly crippled RFC format.   I'm working on it!
