### ISSUE TITLE
I believe that the Cleartext JWS example in Figure 1 is wrong

### ISSUE THREAD

**Issue by selfissued** [erdtman/Cleartext-JOSE#12]
The example has both the __cleartext_header_parameters and __cleartext_signature members at the top level of the JSON structure.  Should the __cleartext_signature member be inside the __cleartext_header_parameters object?

**Comment by cyberphone** [comment]
Yes it should.

Using my [preferred] nomenclature we are dealing with _Signature Objects_ holding a set of _Parameters_.

_Signature Objects_ are intended for inclusion in arbitrary JSON objects (at the top level), effectively making objects digitally signed.

Each JSON object (as well as possible child objects), can hold a maximum of one _Signature Object_.
