### ISSUE TITLE
Test vector "kid" etc.

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#15]
I have a pretty large collection of test vectors for my current incarnation of the Cleartext schemes.
I would like to stick a set of keys throughout the mission even if signatures and encryptions would change every now and then.

The current set of asymmetric keys include an RSA 2048 bit key, a P-256 key, a P-384 key, and a P-521 key.  I'm thinking of (re)naming them to:
- example.com:r2048
- example.com:p256
- example.com:p384
- example.com:p521

These names are also featured in P12 containers which are used for producing the test keys which are not only JWKs but certificate paths for "x5c" and "x5u" as well. 

Would that be OK?

**Comment by erdtman** [comment]
It is awesome with test-vectors!

The names works for me

**Comment by selfissued** [comment]
I agree that we will want test vectors.  Indeed, my initial feedback requested that the keys be put in the spec so people could verify the examples given.

By the way, I put a bunch of comments in the spec as XML comments.  Search for "TBD" in the source to see them.  Sorry I forgot to mention that earlier.  My request for adding the keys is in one of these comments.

That said, I don't think the time is yet right for adding test vectors, as we haven't even agreed on some of the basics of what the spec should do.  For instance, what is the syntax for multiple signatures and how does it relate to the syntax for single signatures?  We should sort out the "what does it do?" questions first before providing detailed examples that depend upon the answers to the "what does it do?" question.

**Comment by selfissued** [comment]
Let's add these after we do the renamings agreed to.
