### ISSUE TITLE
EBNF grammar

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#2]
It is hard describing JWE.  I'm currently exploring different ways of doing that. 

FWIW, I have played a bit with (sort of) EBNF, here in a _very_ primitive way:

```code
encryption object = 'enc', 'iv', 'tag', 'ciphertext', [ key encryption ], [ 'crit' ] ;
key encrytion     = multiple | ( single, [ encrypted_key ]) ;
public key data   = 'jku' | 'x5u' | 'jwk' | 'x5c' ;
multiple          = 'recipients', ":[", { single keywrap }, "]", optional ;
single keywrap    = single, encrypted key ;
encrypted key     = 'encrypted_key' ;
single            = key data, crit properties, optional ;
key data          = [ 'epk' ], [ public key data ] ;
optional          = [ 'alg' ], [ 'kid' ] ;
crit properties   = [ ? custom properties listed in the 'crit' array ? ] ;
```
Constraints for `multiple`:
'alg' or 'kid' properties MUST NOT be defined on both the _Global_ level and inside of `single keywrap`.
`crit properties` MUST NOT be defined on the _Global_ level.

Related: https://github.com/erdtman/jcs/issues/1

**Comment by erdtman** [comment]
I had not heard about EBNF before. COSE (RFC8152) uses CDDL (draft-ietf-cbor-cddl-00) and it has been useful to me when implementing COSE. However I think it should be a complement to text and examples which I think should be focus.

Is there something like this in the JOSE documents?

**Comment by selfissued** [comment]
Developers will code to good examples.  We should emphasize having good examples.

**Comment by selfissued** [comment]
We will close this after we add the examples called for in #15 .
