### ISSUE TITLE
Put back Direct Key Agreement step in JWE processing

### ISSUE THREAD

**Issue by erdtman** [erdtman/Cleartext-JOSE#23]
When Direct Key Agreement or... (removed)
Should not be removed?

**Comment by erdtman** [comment]
When looking at this again I´m not so sure that it should be added back, let me explain:
the step says:
"When Direct Key Agreement or Direct Encryption are employed, verify that the JWE Encrypted Key value is an empty octet sequence."
I think this comes from the compact serialization where one cannot remove just one part from the serialization, but one can leave it empty.

For JSON serialization it is stated in JWE that the encrypted_key MUST not be present in this case 'The "encrypted_key" member MUST be present and contain the value BASE64URL(JWE Encrypted Key) when the JWE Encrypted Key value is non-empty; otherwise, it MUST be absent.'

What we are after is the JSON case, it MUST be absent. I guess that one could interpret the text "verify that the JWE Encrypted Key value is an empty octet sequence." as absent. However I think the text would be better like this "When Direct Key Agreement or Direct Encryption are employed, verify that the JWE Encrypted Key value is absent".

**Comment by cyberphone** [comment]
> When Direct Key Agreement or Direct Encryption are employed, verify that the JWE Encrypted Key value is absent

LGTM
