### ISSUE TITLE
Include non-ASCII Unicode in examples, at least for CT-JWS 

### ISSUE THREAD

**Issue by erdtman** [erdtman/Cleartext-JOSE#24]
<!— TBD Include non-ASCII Unicode characters in the example, such as a UK Pound symbol and/or a Euro currency symbol -->

Document encoding needs to be changed

**Comment by erdtman** [comment]
I asked about unicode and got the following answer

    HI Samuel,

    This won't work for you yet. That's part of the new format work, and the documents published so far with non-ASCII characters were really to test the system. Here's what's in the FAQ:

    UTF-8 characters will be allowed once the v3 tools have been fully tested and moved into the RPC’s production tool chain. While a few exceptions (RFCs 8187, 8264, 8265, and 8266) were published before the v3 tools were available, these were used as test cases to fully understand the requirements for allowing UTF-8 in RFCs. For more details, see the mail from the RFC Series Editor on this topic.

    https://www.rfc-editor.org/rse/format-faq/#3

    I hope that helps!

Based on that maybe we should wait a bit with the unicode characters :(

**Comment by selfissued** [comment]
OK
