### ISSUE TITLE
JWK interoperability issues

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#25]
If you take the JOSE specifications literally, it seems that constructs like the following would be legal:

```code
 "kid":" mykey",
 "jwk": {
   "kid": "mykey",
   "x5c": ["MI..........................................."]
```
 
In my [sort of] "reference implementation", a supplied JWK may only contain a public key, _everything else is flagged as an error_.  JWE indeed says that a JWK contains a public key but doesn't say anything about possible additional properties except for `"kid"` which is supposed to be "matched". Non-matches => fail?

I do not propose improving the matching text, I rather want to remove things that only add "fuzz".  I.e. JWK would when hosted in Cleartext JW*, be a _profiled version_ of the JWK standard.

**Comment by selfissued** [comment]
This kind of tinkering at the edges of the existing JOSE semantics is out of scope for this effort, because it goes beyond our goal of replacing base64url encoding with ES6 canonicalization, where applicable.
