### ISSUE TITLE
JKU interoperability issues

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#26]
That a JKU points to an arbitrary JWK key set in my opinion creates major interoperability issues.  I can't imagine that anybody out there actually tries out different keys in order to verify signatures or decrypt data.

In my [sort of] "reference implementation" I have addressed this problem by restricting key sets to a _single element_: https://cyberphone.github.io/doc/openkeystore/p256.jwks

Another possibility would be that a JKU also implies the presence of an in-line JWK for avoiding the trial-and-error scheme.

**Comment by cyberphone** [comment]
Key selection is usually performed on the _sender's_ side.  Not clearly informing the receiver which key was eventually selected is simply put a bug.

Although we all agree that reusing the JOSE specifications is a goal, inheriting obvious design flaws is IMO taking backward compatibility too far.  The most straightforward solution _(for the the Cleartext JSON specifications only_), is redefining JKU to rather point to a JWK. 

My current one-element key set restriction is a "workaround", not worthy standardization. 

WDYT?

**Comment by selfissued** [comment]
Anders, you misunderstand the feature and its purpose.  The ability to reference a set of keys is essential to performing key roll-over - a critical security function.  The "kid" (key ID) value is typically used to indicate which member of the key set was employed.  There is no "key guessing".

For an example of how JWK sets are used for key roll-over in a production system, see http://openid.net/specs/openid-connect-core-1_0.html#Signing.

If we're to convince people to make the Cleartext JOSE work a standard, we MUST ruthlessly keep the scope of the work narrow and specific: replacing base64url encoding with ES6 canonicalization, where applicable.  And that's it.  Everything else is out of scope.

If we start randomly departing from JOSE in other ways, we'll lose all credibility and fail to achieve standardization.

In the future please, before criticizing an existing JOSE feature on the JOSE mailing list, please check with me first to understand why the existing specs are they way they are.  If we lose credibility with the JOSE mailing list members, our effort will almost certainly fail.

**Comment by cyberphone** [comment]
Mike,
I took a peek at:
http://openid.net/specs/openid-connect-core-1_0.html#Signing

_"If there are multiple keys in the referenced JWK Set document, a kid value MUST be provided in the JOSE Header"_

This fully verifies my claim that JKU as a _stand alone attribute_ is not overly useful.  As I understand you want us to ignore that.  That may be, but in the reference implementation and test suite I don't really have this "luxury" :-)

Pardon for bringing up this topic on the JOSE list before checking with you.  Anyway, I learnt something new: _True_ "Key Guessing" is apparently considered a viable method.  I won't bother with that in the test suite though.
