### ISSUE TITLE
Naming the standards-to-be

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#3]
If these work items receive JOSE support it would (for marketing reasons) be a good idea reusing the names of the standards as well.  JWS/X and JWE/X are possible names where 'X' denotes e**X**tended or whatever you want :-)

Adding a **-CT** suffix for **C**lear **T**ext also sounds reasonable.

**Comment by erdtman** [comment]
+1 on keeping names close to current JOSE specifications.

I would prefer CT prefix (or suffix) i.e. Cleartext JWS and Cleartext JWE.
The JWE one becomes a bit confusing with the combination of cleartext and encryption (but to me it works).

**Comment by cyberphone** [comment]
> The JWE one becomes a bit confusing with the combination of cleartext and encryption (but to me it works).

Indeed, this is why I came up with this "nonsensical" suffix **X** :-) 

Anyway, anything works for me as long as the root (origin) is there.

**Comment by erdtman** [comment]
I think we can close this with the merge of Mikes PR.

Correct?

**Comment by selfissued** [comment]
Agreed - please close
