### ISSUE TITLE
The "crit" extension for multi-signatures

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#38]
Just to verify that we are on the same page, here is a genuine sample:
```json
{
  "now": "2018-04-16T11:23:06Z",
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "__cleartext_signature": {
    "crit": ["myString","https://example.com/extension"],
    "signers": [{
      "alg": "ES256",
      "jwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
        "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY"
      },
      "myString": "some data",
      "https://example.com/extension": {
        "life-is-great": true
      },
      "signature": "rJUW8xr6_UgyqA_JIc519PLSM0q9kO4D-bLyBeBu-0z8wn46wEaUJCq5vvElPbgHuO7ACKQmrSm74k_FZrZBCw"
    },{
      "alg": "ES512",
      "jwk": {
        "kty": "EC",
        "crv": "P-384",
        "x": "GLfdsvEwphRzS_twup7UFPVOk7_CKgHZ7dt_fJ2QHPBdJa1c5pfJcRIWTfT0lpg9",
        "y": "ovA5_QXmFbj9U4pjZ1AX_ZdVyIRZUBWW9cuZda_tupKfWQfmcQHzDmHGHbxl9Xxl"
      },
      "myString": "other data",
      "https://example.com/extension": {
        "life-is-great": true
      },
      "signature": "T6MMaUABjJ10Q63IVbnIylmuA1QYAS1iLfkgxBPczJSLMPHz8TQ8z4xA-Lc0T7VU83XhnybMLRfEsu5QmXqtkQo3obqcGRJm0ucOb1ixlN8NRUy15w_IcW111-wX1oxY"
    }]
  }
}
```
Rules:
- The "crit" extension must only exist on the global/outer level
- The arguments themselves must only exist in the local/inner level

That is, the "crit act as a declarator for _all_ the signatures.

I believe my implementation does something worth mentioning in the draft: A conforming implementation SHOULD NOT accept _Signature Objects_ holding unknown extensions.

**Comment by selfissued** [comment]
I don't see a reason to limit "crit" to the global level.  However, the normal rule that a header parameter value must only exist on one level would still apply.

What do you mean by "unknown extensions"?  As with all JOSE header parameters (and most JSON usage), not-understood header parameters MUST be ignored - unless their names are in the "crit" list.

**Comment by cyberphone** [comment]
> I don't see a reason to limit "crit" to the global level. However, the normal rule that a header parameter value must only exist on one level would still apply.

I'm lazy :-)  Your'e right, will update.

> What do you mean by "unknown extensions"? As with all JOSE header parameters (and most JSON usage), not-understood header parameters MUST be ignored - unless their names are in the "crit" list.

In my "reference implementation" non-recognized elements are rather flagged as hard errors but if you prefer ignored in the draft, I can live with that.

**Comment by cyberphone** [comment]
Better now?
```json
{
  "now": "2018-04-16T11:23:06Z",
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
  "signature": {
    "signers": [{
      "alg": "ES256",
      "jwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "censDzcMEkgiePz6DXB7cDuwFemshAFR90UNVQFCg8Q",
        "y": "xq8rze6ewG0-eVcSF72J77gKiD0IHnzpwHaU7t6nVeY"
      },
      "crit": ["https://example.com/extension"],
      "https://example.com/extension": {
        "life-is-great": true
      },
      "val": "CUTl2LAzx53jimVi3qDfgz0tiTEX5bwR3CHKru5s9WQ6d-_k2URAC-eDjA3yD5rwpiIevXmscu8p6gqdd79yFA"
    },{
      "alg": "ES512",
      "jwk": {
        "kty": "EC",
        "crv": "P-384",
        "x": "GLfdsvEwphRzS_twup7UFPVOk7_CKgHZ7dt_fJ2QHPBdJa1c5pfJcRIWTfT0lpg9",
        "y": "ovA5_QXmFbj9U4pjZ1AX_ZdVyIRZUBWW9cuZda_tupKfWQfmcQHzDmHGHbxl9Xxl"
      },
      "crit": ["myString"],
      "myString": "other data",
      "val": "KfGmvyPpgHnC7xIbLinqHNI73y6WNQu4vYJNmRdtB4OvkzCp96QUcuCRl9V_IE5n0x51d-f8tA7u3qoF05z5EprayP8rIuoKakcYSI-LQjgkaeIQQRwk41p2fkAdYBK5"
    }]
  }
```

**Comment by erdtman** [comment]
Looks good to me!

**Comment by erdtman** [comment]
@cyberphone Do we need to update the text to reflect this? or can we close this now?

**Comment by cyberphone** [comment]
It seems that we agree on the spec, so we just need to get it straight in I-D

**Comment by selfissued** [comment]
I'll plan on reviewing the text on this.
