### ISSUE TITLE
The default "__cleartext_signature" property?

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#40]
The current draft AFAICT still talks about MUST while we have discussed a default.

I don't know how to express this in a draft since defaults are usually applied when information is missing.  Maybe you guys have an idea?

To me it still seems easier and better redefining Cleartext JWS as a _Signature Object,_ behaving more less as any other derived data type.  This at least what my "reference implementation" does, here featured in a payment provider system I've recently been involved in:

```java
public class PSPRequest {

    static final String MERCHANT_ID  = "merchantId";
    static final String REFERENCE_ID = "referenceId";
    static final String CURRENCY     = "currency";
    static final String AMOUNT       = "amount";
    static final String CARD_DETAILS = "cardDetails";
    static final String TIME_STAMP   = "timeStamp";
    static final String SIGNATURE    = "signature";

    public static JSONObjectWriter encode(String merchantId,
                                          String referenceId,
                                          Currencies currency,
                                          BigDecimal amount,
                                          CardDetails cardDetails,
                                          ServerAsymKeySigner signer) throws IOException {
        return new JSONObjectWriter()
            .setString(MERCHANT_ID, merchantId)
            .setString(REFERENCE_ID, referenceId)
            .setString(CURRENCY, currency.toString())
            .setBigDecimal(AMOUNT, amount, currency.getDecimals())
            .setObject(CARD_DETAILS, cardDetails.writeObject())
            .setDateTime(TIME_STAMP, new GregorianCalendar(), true)
            .setSignature(SIGNATURE, signer);
    }

    String merchantId;
    String referenceId;
    Currencies currency;
    BigDecimal amount;
    GregorianCalendar timeStamp;
    CardDetails cardDetails;
    PublicKey publicKey;
    
    public PSPRequest(JSONObjectReader rd) throws IOException {
        merchantId = rd.getString(MERCHANT_ID);
        referenceId = rd.getString(REFERENCE_ID);
        currency = Currencies.valueOf(rd.getString(CURRENCY));
        amount = rd.getBigDecimal(AMOUNT, currency.getDecimals());
        cardDetails = new CardDetails(rd.getObject(CARD_DETAILS));
        timeStamp = rd.getDateTime(TIME_STAMP);
        publicKey = rd.getSignature(SIGNATURE, new JSONSignatureDecoder.Options()).getPublicKey();
        rd.checkForUnread();
     }
}
```
If any element is _unknown_, _missing_, or _malformed_, the PSPRequest object is rejected.

A schema based approach would presumably do the same.

**Comment by cyberphone** [comment]
Using JWS the signature indeed "takes over" the application.  This differs from Cleartext JWS where a signature is intended to be a part of the application data.

An enveloped _Signature Object_ may also (like any other application data), be specified as _optional_.  As a consequence, the algorithm "none" doesn't appear to fill a need in Cleartext JWS.

**Comment by erdtman** [comment]
I can try to formulate something for this

**Comment by selfissued** [comment]
The normal way to do this is to use a "MUST ... unless" construction, as is done several places in JOSE.

The language that I would recommend is along the lines of "The identifier for the Cleartext Signature structure MUST be "__cleartext_signature", unless the application specifies that a different identifier is to be used.

**Comment by cyberphone** [comment]
> The language that I would recommend is along the lines of "The identifier for the Cleartext Signature structure MUST be "__cleartext_signature", unless the application specifies that a different identifier is to be used

Feel free doing that although this doesn't really parse in my head.   My interpretation is something like:

"Although there's a strong preference for using `__cleartext_signature`, you may actually use whatever name you think is applicable"

**Comment by erdtman** [comment]
To me it sounds like a default, if the application does not specify something you must use `__cleartext_signature`
