### ISSUE TITLE
Test/Sample in data

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#41]
The current Cleartext JWS I-D shows an example with data-to-be-signed:

```json
"iss":"joe",
"exp":1300819380,
"http://example.com/is_root":true
```

My current test vectors do not.  I can update the whole bunch to use the above.  OK?

For encryption I have used:
 
```code
Hello encrypted world!
```

OK?

**Comment by selfissued** [comment]
Fine by me

**Comment by erdtman** [comment]
I changed from your examples to whats in now to keep it close to the JWS document.
However I think it makes sense to have the tricker stuff in there as you have it maybe by doing it like this:

```
  "iss":"joe",
  "exp":1300819380,
  "escapeMe": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
  "numbers": [1e+30,4.5,6],
```

Long term we would like to get some unicode characters in too, see #24

**Comment by selfissued** [comment]
+1 to using \u forms to include non-ASCII characters.

**Comment by cyberphone** [comment]
I will do that later today in my test vector collection

**Comment by erdtman** [comment]
I like the Idea to move keys to test vector section

**Comment by selfissued** [comment]
Fine by me too.
