### ISSUE TITLE
Bikeshedding on property names for IANA registering

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#5]
JWS/JWE defines a bunch of attributes that are IANA registered.
The attributes that are added in the JSON serialization variants are though _not registered_.
In the revised scheme _all_ attributes would(?) be candidates for IANA registration.

Although not important a JWE property like `ciphertext` doesn't feel entirely right since it
- departs from current JSON naming standards like `cipherText` and `cipher_text`.
- departs from other registered JOSE attributes which are 1-4 characters

**Comment by erdtman** [comment]
I think the 1-4 character names stems from the desire to save on space when sending tokens as part of URLs, that is not an issue for us so I would go with longer names to lessen confusion.

When it comes to attributes like ciphertext I would like it to go in line with 'encrypted_key' that is defined in JWE i.e. use underscore.

**Comment by cyberphone** [comment]
This is where the "bikeshedding" comes in, there are now not less than 3(!) proposals on the table :-)
1.  Keep "as is"
2.  Stylistically align the new IANA attributes with the existing IANA attributes which already have crummy names like `enc` and `epk`
3.  Update `ciphertext` to follow the `open_id` kind of naming standard

Since `ciphertext `and `encrypted_key` (unlike `alg`, `kid`, and `jwk`) do not contain anything an _application developer_ could have any interest in, my preference is **2** but I accept **_any_** of them.

**Comment by erdtman** [comment]
I realize that to me ciphertext was one word (see [wiki](https://en.wikipedia.org/wiki/Ciphertext)), if that is not correct I could go in either direction.

I like the uniformity of keeping names similar to the current JOSE practice, but then I would like to shorten encrypted_key too and then we are taking the first step away from JWE.

@selfissued do you have a strong opinion here?

**Comment by cyberphone** [comment]
I had to look it up.  I believe ciphertext is a "compound word" that after many years have become like an ordinary word.  GitHub still flags it as wrong...

I found this after some search:  https://tools.ietf.org/html/rfc4949
```code
$ cipher text
      1. (I) /noun/ Data that has been transformed by encryption so that
      its semantic information content (i.e., its meaning) is no longer
      intelligible or directly available. (See: ciphertext. Compare:
      clear text, plain text.)
```
As a member of the JSON "art club", I'm a little bit obsessed by uniformity but I realize that not everybody is :-)

**Comment by selfissued** [comment]
The names signature, signers, and recipients should be registered by the JWS draft.  Also ciphertext and encryption_key would be registered in the JWE draft.

**Comment by selfissued** [comment]
IANA registrations for "signature" and "signers" are now present in the Cleartext JWS draft and "ciphertext", "encrypted_key", and "recipients" are now present in the Cleartext JWE draft. I believe that this addresses the IANA registration issues.
