### ISSUE TITLE
New IANA registered attribute for Signature Value

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#7]
I started with "value" but then I after consulted Samuel ended up with "val" following the spirit of "alg", "jwk", "kid" etc.

Seen in retrospect we have now created a rather weird set of names where the revised JVS uses "val" for denoting signature value while JWE uses "ciphertext" to denote its counterpart.

I certainly do not advocate for using "signaturevalue", I only wanted to raise the issue.

A difference with the original JOSE standards is that _header data is now visible and therefore will be exposed to more interest than before_.

See https://github.com/erdtman/Cleartext-JOSE/issues/5

**Comment by selfissued** [comment]
"val" seems to be in danger of collisions with application's name usage.

Thinking about the cleartext specs before I knew that I would be able to participate, it came to me that the cleartext names probably should be clearly disginguished from the other JSON member names with which they are are intermixed.  ANSI C uses the prefix "__" (two underscores) to do this.  I would advocate that we do the same.

So for instance, I'd put the signature in a member with the name "__sig".

**Comment by cyberphone** [comment]
> "val" seems to be in danger of collisions with application's name usage.

If you take a look at the proposed structure all JWS header attributes reside in a _sub object_, below the application level.  You are not supposed to put application data there.  If you do, you **must** add a "crit" declarator.

The signature variant is essentially a very simplified "remake" of enveloped XML DSig by adding a `signature` property to an arbitrary JSON or JavaScript object ({ }).

**Comment by erdtman** [comment]
I would vote for two attributes 
'signature' or 'sig' for the signature value and 'ciphertext' or 'cip' for encrypted value. This solution makes it most readable.

As Anders mentioned we should not need to worry about the attribute/header names to conflict with application attributes in general since they will be wrapped in there own object. However I like the idea of two underscores ('__') prefix when it comes to the signature/signatures attribute that could actually conflict with application attributes.
Something like this
 `
{
  // application attributes
  __signature {
    // Signature attributes/headers
  }
}
`

**Comment by cyberphone** [comment]
> However I like the idea of two underscores ('__') prefix when it comes to the signature/signatures attribute that could actually conflict with application attributes.

I would prefer keeping 'signature'  as described in https://github.com/erdtman/Cleartext-JOSE/issues/9 which makes it possible (and still being standards conformant), using something else in the hopefully pretty rare case 'signature' would clash with the application.

**Comment by selfissued** [comment]
IANA registrations for "signature" and "signers" are now present in the Cleartext JWS draft and "ciphertext", "encrypted_key", and "recipients" are now present in the Cleartext JWE draft. I believe that this addresses the IANA registration issues.
