### ISSUE TITLE
Keeping the "x5c" legacy or not?

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#8]
The "x5c" attribute departs from all other JOSE attributes by requiring the binary data to be Base64-encoded rather than using Base64Url.

Personally, I would consider changing this to make it "neater".  There is no legacy to bother with either.  Dealing with this in libraries combining the original JOSE standards as well as the CT counterparts must be a very small thing.

But I wait for your "verdict" :-)

**Comment by selfissued** [comment]
x5c is base64 encoded because that's what PEM encoding of certificates does.  This allows PEM encoded values to be just copied into the x5c claim without transformation.  This was an intentional choice that we should maintain.

**Comment by cyberphone** [comment]
Since "x5c" isn't PEM compatible I do not really think this is a valid argument, but I buy it anyway :-)
